Fix captcha generation on docker stack
simde-utc/portail pull request #196
Opened 2019-03-31 12:36 UTC by courentin

Gd était mal configuré pour son installation. La generation du captcha donnait l'erreur suivant : 
```
[2019-03-31 12:52:42] develop.ERROR: Call to undefined function Intervention\Image\Gd\imagettfbbox() {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Call to undefined function Intervention\\Image\\Gd\\imagettfbbox() at /var/www/vendor/intervention/image/src/Intervention/Image/Gd/Font.php:85)
[stacktrace]
```

2019-03-31 13:13 UTC, NastuzziSamy submitted a review, later dismissed
Bien vu @courentin, merci ! :) 

@cesar-richard tu peux review stp ?

2019-03-31 16:35 UTC, cesar-richard requested changes

2019-03-31 16:35 UTC, cesar-richard commented on docker/app.dockerfile
> +RUN apt-get -o Acquire::Check-Valid-Until=false update && apt-get install --no-install-recommends -y libmcrypt-dev gnupg git unzip \
Je ne suis pas d'accord sur la désactivation de sécurités sur un environnement de dev/testing/staging

2019-03-31 16:35 UTC, cesar-richard commented on docker/app.dockerfile
> +RUN echo "deb [check-valid-until=no] http://archive.debian.org/debian jessie-backports main" > /etc/apt/sources.list.d/jessie-backports.list
Why ?

2019-03-31 16:35 UTC, cesar-richard commented on docker/app.dockerfile
> +RUN sed -i '/deb http:\/\/deb.debian.org\/debian jessie-updates main/d' /etc/apt/sources.list
Très sale

2019-03-31 16:35 UTC, cesar-richard commented on docker/app.dockerfile
> +    mysql-client libmagickwand-dev libfreetype6-dev libwebp-dev libjpeg62-turbo-dev libpng-dev \
Tu as besoin des packages -dev pour juste utiliser ? Les normaux ne suffisent pas ?

2019-04-08 17:25 UTC, NastuzziSamy commented
@courentin @cesar-richard  ça en est où ici ?

2019-04-08 20:52 UTC, courentin commented
Prêt à review !

2019-04-14 15:15 UTC, cesar-richard approved these changes

2019-04-14 16:43 UTC, merged