Fix/update docker
simde-utc/portail pull request #199
Opened 2019-04-01 08:53 UTC by cesar-richard

2019-04-01 10:12 UTC, NastuzziSamy requested changes
Ca à l'air dêtre bon mais les 32 commtis là, me posent problème.

Tu peux rouvrir une PR avec seulement tes modifs et le dernier commit sur develop ?

2019-04-01 11:57 UTC, cesar-richard commented
> Ca à l'air dêtre bon mais les 32 commtis là, me posent problème.
> 
> Tu peux rouvrir une PR avec seulement tes modifs et le dernier commit sur develop ?
@NastuzziSamy 
Globalement , non la flemme #pasletemps.
Ouai j'ai chopé tous les commits parce que j'avais zapé de pull avant de commit mes modifs donc le pull a posteriori affiche ca. Cependant le diff est bon alors blc.

2019-04-01 12:37 UTC, cesar-richard commented
> > Ca à l'air dêtre bon mais les 32 commtis là, me posent problème.
> > Tu peux rouvrir une PR avec seulement tes modifs et le dernier commit sur develop ?

@NastuzziSamy
Globalement , non la flemme #pasletemps.
Ouai j'ai chopé tous les commits parce que j'avais zapé de pull avant de commit mes modifs donc le pull a posteriori affiche ca. Cependant le diff est bon alors blc.

2019-04-01 16:16 UTC, merged

2019-04-04 13:25 UTC, courentin commented on docker/app.dockerfile
> -FROM php:7.1.3-fpm
Pourquoi ? On a besoin de fpm ?

2019-04-04 13:25 UTC, courentin commented on docker/vhost.conf
> +        fastcgi_pass app;
Sans spécifier le port, j'ai une jolie : 
```
[emerg] 1#1: no port in upstream "app" in /etc/nginx/conf.d/default.conf:12
```

Le port semble requis : https://stackoverflow.com/a/23915826/5619020

2019-04-04 13:25 UTC, courentin commented on docker-compose.yml
> +      - ./vendor:/var/www/html/vendor
Redondant ?

2019-04-04 13:25 UTC, courentin commented on docker-compose.yml
> +      - ./:/var/www/html
à enquêter mais en ajoutant html j'ai une 404 du container app et une erreur sur le container nginx : 
```
[error] 6#6: *2 FastCGI sent in stderr: "Primary script unknown" while reading response header from upstream,
```

2019-04-04 14:18 UTC, cesar-richard commented
@courentin L'Homme qui review des PR merged :)