Feature: Documentation Translation
simde-utc/portail pull request #250
Opened 2019-07-10 21:07 UTC by MercierCorentin

In this PR I translated the documentation folder of the project. 
There might be some mistakes as it's a long work but I can't see them.

2019-07-20 12:19 UTC, NastuzziSamy approved these changes
I've not read everything but they are some ridiculous mistakes haha 

Good job ^^

2019-07-20 12:19 UTC, NastuzziSamy commented on documentation/README.md
>      - [Authentification](backend/oauth.md)
Authentication

2019-07-20 12:19 UTC, NastuzziSamy commented on documentation/README.md
> +We are also going to show how to intercact with the api in differents languages. For instance, we will give examples of connexion code to the api in js, php and python.
interact*
different*
connection*
exemples of API connection code*

2019-07-20 12:19 UTC, NastuzziSamy commented on documentation/README.md
> +Its goal is to document thearchitecture, the created services, the controllers, the models and so on in order to give this project some durability. It doesn't aim to recreate Laravel's documentation.
the arch*

2019-07-20 12:19 UTC, NastuzziSamy commented on documentation/backend/authentification.md
> +`class` corresponds to the authentification service and `model` to the model.
authentication

2019-07-20 12:19 UTC, NastuzziSamy commented on documentation/backend/documentation.md
> +make sure you've installed all necessary packages trough `composer update`.
through*

2019-07-20 12:19 UTC, NastuzziSamy commented on documentation/backend/models.md
> +Namespace : `\App\Models\...` <br>
<br> ?

2019-07-20 12:19 UTC, NastuzziSamy commented on documentation/backend/oauth.md
> +*(customized by Samy because he's a beast)*
@abrasseu x)

2019-07-20 12:19 UTC, NastuzziSamy commented on documentation/backend/oauth.md
> +A token is a triplet (`client`, `user`, `scopes`).This token is retrieved by an association's `client` (Wich is an API, a Webwite, an Interface) or a user (connected user or personnal API).
which*

2019-07-20 12:38 UTC, NastuzziSamy requested changes
Fix everything before :)

2019-07-20 12:41 UTC, huetremy commented
Il think it is a good idea to provide an english version of the documentation, but why removing the french version ? Could we keep both ?

2019-07-20 12:44 UTC, NastuzziSamy commented
@huetremy was decided here: https://github.com/simde-utc/portail/issues/242

=> Everything in english now

2019-07-20 12:49 UTC, huetremy commented
@NastuzziSamy ok for the code and the PR/issues, but why **removing** some french documentation that already exists ?

2019-07-20 12:51 UTC, huetremy commented
I mean it does already exist si we could keep it for people who does not understand english ^^

2019-07-20 12:51 UTC, NastuzziSamy commented
@huetremy no debate in PR.

2019-07-20 12:55 UTC, huetremy commented
@NastuzziSamy what is the aim of a PR but discussing about modifications a person wants to makes to a project ? :confused:

2019-07-20 13:37 UTC, huetremy requested changes
Some corrections :)

2019-07-20 13:37 UTC, huetremy commented on documentation/api/readme.md
> +The API is currently uder the first version. All URLs have the form : `https://assos.utc.fr/api/v1/{requete}`
```suggestion
The API is currently under the first version. All URLs have the form : `https://assos.utc.fr/api/v1/{request}`
```

2019-07-20 13:37 UTC, huetremy commented on documentation/backend/authentification.md
>  # Authentification
```suggestion
# Authentication
```

2019-07-20 13:37 UTC, huetremy commented on documentation/backend/authentification.md
> +The authentification system is a modular one.
```suggestion
The authentication system is modular.
```

2019-07-20 13:37 UTC, huetremy commented on documentation/backend/authentification.md
> +Each authentification type is described in `config/auth.php`, in the array `services`.
```suggestion
Each authentication type is described in `config/auth.php`, in the array `services`.
```

2019-07-20 13:37 UTC, huetremy commented on documentation/backend/authentification.md
> +Each authentification system is declared in `config/auth.php => services` this way:
```suggestion
Each authentication system is declared in `config/auth.php => services` this way:
```

2019-07-20 13:37 UTC, huetremy commented on documentation/backend/authentification.md
> +## Parent authentification service
```suggestion
## Parent authentication service
```

2019-07-20 13:37 UTC, huetremy commented on documentation/backend/authentification.md
> +Located in `app/Services/Auth/AuthService.php`, it is an abstract class that each authentication service must implements.
```suggestion
Located in `app/Services/Auth/AuthService.php`, it is an abstract class that each authentication service must implement.
```

2019-07-20 13:37 UTC, huetremy commented on documentation/backend/authentification.md
> +## Specific authentification service
```suggestion
## Specific authentication service
```

2019-07-20 13:37 UTC, huetremy commented on documentation/backend/authentification.md
> +It must inherits from the `App\Services\Auth\AuthService` parent authentification service.
```suggestion
It must inherit from the `App\Services\Auth\AuthService` parent authentification service.
```

2019-07-20 13:37 UTC, huetremy commented on documentation/backend/authentification.md
> +Methods and attributes that it must inherits and that must be implemented are:
```suggestion
Methods and attributes that it must inherit and that must be implemented are:
```

2019-07-20 13:37 UTC, huetremy commented on documentation/backend/authentification.md
> +Must contain the necessary data for the connection trough the specific system, a foreign key the the linked user and a `last_login_at` timestamp.
```suggestion
Must contain the necessary data for the connection through the specific system, a foreign key the the linked user and a `last_login_at` timestamp.
```

2019-07-20 13:37 UTC, huetremy commented on documentation/backend/commenter.md
> +The SiiMDE uses the convention [DocBlock](http://docs.phpdoc.org/guides/docblocks.html#anatomy-of-a-docblock).
```suggestion
The SiMDE uses the convention [DocBlock](http://docs.phpdoc.org/guides/docblocks.html#anatomy-of-a-docblock).
```

2019-07-20 13:37 UTC, huetremy commented on documentation/backend/controllers.md
> +Dossier :   `app/Http/Requests`
```suggestion
Folder :   `app/Http/Requests`
```

2019-07-20 13:37 UTC, huetremy commented on documentation/backend/documentation.md
> +The command tu update the documentation is:
```suggestion
The command to update the documentation is:
```

2019-07-20 13:37 UTC, huetremy commented on documentation/backend/oauth.md
> +A token is a triplet (`client`, `user`, `scopes`).This token is retrieved by an association's `client` (Wich is an API, a Webwite, an Interface) or a user (connected user or personnal API).
```suggestion
A token is a triplet (`client`, `user`, `scopes`). This token is retrieved by an association's `client` (Which is an API, a Website, an Interface) or a user (connected user or personal API). 
```

2019-07-20 13:37 UTC, huetremy commented on documentation/backend/oauth.md
> +This middlewares are automatically generated by the facede `Scopes`.
```suggestion
This middlewares are automatically generated by the facade `Scopes`.
```

2019-07-20 13:37 UTC, huetremy commented on documentation/backend/oauth.md
> +The `Scopes` façade simplifies Scopes usage.
```suggestion
The `Scopes` facade simplifies Scopes usage.
```

2019-07-20 13:37 UTC, huetremy commented on documentation/backend/oauth.md
> +Some similar functions retur an boolean instead of authorizing trough some middlewares.
```suggestion
Some similar functions return an boolean instead of authorizing trough some middlewares. 
```

2019-07-20 13:37 UTC, huetremy commented on documentation/backend/services.md
> +Services aim to implement external APIs or particular functionnalities such as Ginger or the CAS.
```suggestion
Services aim to implement external APIs or particular functionalities such as Ginger or the CAS.
```

2019-07-20 13:37 UTC, huetremy commented on documentation/backend/services.md
> +To create a new services/authentification system, just create a child class of the AuthService.php service and ovveride the parent functions.
```suggestion
To create a new services/authentication system, just create a child class of the AuthService.php service and override the parent functions.
```

2019-07-20 13:37 UTC, huetremy commented on documentation/backend/services.md
> +## Central Authentification Service (CAS)
```suggestion
## Central Authentication Service (CAS)
```

2019-07-20 13:37 UTC, huetremy commented on documentation/backend/services.md
> +The CAS is an authentification service automatically managed by the created CAS service. It handles automatically logins and logouts.
```suggestion
The CAS is an authentication service automatically managed by the created CAS service. It handles automatically logins and logouts. 
```

2019-07-20 13:37 UTC, huetremy commented on documentation/backend/traits.md
> +PHP functionnality to reduce some limitations of single inheritance.
```suggestion
PHP functionality to reduce some limitations of single inheritance.
```

2019-07-20 13:37 UTC, huetremy commented on documentation/frontend/readme.md
> +## Developement
```suggestion
## Development
```

2019-07-20 13:37 UTC, huetremy commented on documentation/frontend/readme.md
> +To run the developement server BrowserSync:
```suggestion
To run the development server BrowserSync:
```

2019-07-20 13:37 UTC, huetremy commented on documentation/frontend/readme.md
> +- Make sure you've cofigure `APP_URL` in the file `.env` with the Laravel server adress.
```suggestion
- Make sure you've configured `APP_URL` in the file `.env` with the Laravel server address.
```

2019-07-20 13:37 UTC, huetremy commented on documentation/frontend/readme.md
> +- The developement server runs on the port 3000 by default.
```suggestion
- The development server runs on the port 3000 by default.
```

2019-07-20 13:37 UTC, huetremy commented on documentation/frontend/readme.md
> +- The display is reload at every change in the files.
```suggestion
- The display is reloaded at every change in the files.
```

2019-07-20 13:37 UTC, huetremy commented on documentation/frontend/redux.md
> +First, we have to define **action types**. They are constant strings which unable to identify actions to perform in the different reducers. It is recommanded to define them in the `types.js` file. In
```suggestion
First, we have to define **action types**. They are constant strings which enable to identify actions to perform in the different reducers. It is recommended to define them in the `types.js` file. In order to define CRUD actions sets more easily, use [`createCrudTypes`](#Action-types-creaters).
```

2019-07-20 13:37 UTC, huetremy commented on documentation/frontend/redux.md
> +Actions are objects that are scattered in the reducers. they generally content in a `type` and in a `payload`. They are defined in the `actions.js` file.
```suggestion
Actions are objects that are scattered in the reducers. They generally contain a `type` and a `payload`. They are defined in the `actions.js` file.
```

2019-07-20 13:37 UTC, huetremy commented on documentation/frontend/redux.md
> +Reducers are fonctions with the following prototype: `function(prevState, action)`.
```suggestion
Reducers are functions with the following prototype: `function(prevState, action)`.
```

2019-07-20 13:37 UTC, huetremy commented on documentation/frontend/redux.md
> +As th portal's api mainly follows CRUD (Create Read Update Delete) design, most part of the Redux actions also follows it. That is why we have created creaters of action types, of actions and of CRUD
```suggestion
As the portal's api mainly follows CRUD (Create Read Update Delete) design, most part of the Redux actions also follow it. That is why we have created creators of action types, of actions and of CRUD reducers. These functions are in `react/utils.js`.
```

2019-07-20 13:37 UTC, huetremy commented on documentation/frontend/redux.md
> +### Action types creaters
```suggestion
### Action types creators
```

2019-07-20 13:37 UTC, huetremy commented on documentation/frontend/redux.md
> +- `uri` : the url piece located after the domain name. It unables to access the right resource in the API. For example `assos` unables to access to `https://assos.utc.fr/api/v1/assos`
```suggestion
- `uri` : the url piece located after the domain name. It enables to access the right resource in the API. For example `assos` enables to access to `https://assos.utc.fr/api/v1/assos`
```

2019-07-20 13:37 UTC, huetremy commented on documentation/frontend/redux.md
> +### Creater of reducer
```suggestion
### Creator of reducer
```

2019-07-20 13:37 UTC, huetremy commented on documentation/frontend/redux.md
> +- `overrides` : an object unabling to replace and to add actions gestions to the reducer.
```suggestion
- `overrides` : an object that enable to replace and to add actions managing to the reducer.
```

2019-07-20 13:37 UTC, huetremy commented on documentation/frontend/redux.md
> +which corresponds to (in a simplified way) à :
```suggestion
which corresponds to (in a simplified way) :
```

2019-07-21 11:42 UTC, NastuzziSamy approved these changes
I let you merge this one if you think it is ok

Again, great job :)

2019-07-21 13:38 UTC, merged