Feature: app folder translation
simde-utc/portail pull request #253
Opened 2019-07-13 23:36 UTC by MercierCorentin

In this PR @CdRom1 and I translated the `app` folder.
Part of #242 resolution.

2019-07-19 13:07 UTC, CdRom1 commented
@MercierCorentin you did almost everything and that is a huuuge work gg. You did some typos but they don't prevent from understanding so I won't fix them. Let me just push a few fixes and I'll approve this PR.

2019-07-19 13:17 UTC, CdRom1 commented
@MercierCorentin you only had forgotten **one line** amongst *thousands* 👏💪😗😱

2019-07-19 13:21 UTC, r0one submitted a review, later dismissed

2019-07-20 12:35 UTC, NastuzziSamy requested changes
Huge PR, need to fix the 3rd person before

2019-07-20 12:35 UTC, NastuzziSamy commented on app/Admin/Controllers/Management/AccessController.php
> + * Manages accesses.
Same for everyone, not 3rd person

2019-07-26 14:23 UTC, merged