#14 Events with calendar
simde-utc/portail pull request #26
Opened 2018-11-28 11:43 UTC by arthurlefevre

~2H

2018-11-28 11:52 UTC, NastuzziSamy requested changes
Fais attention, tu indentes de 2, au lieu de 4. Ca crée des conflits partout, je te laisse revenir à 4.

Pense à lancer `php artisan quick:test` avant de push au passage ^^

2018-11-28 11:52 UTC, NastuzziSamy commented on resources/assets/react/components/Calendar/Calendar.js
> +		console.table(events);
`console.table(events)` oublié ^^

2018-11-28 11:52 UTC, NastuzziSamy commented on database/seeds/EventsTableSeeder.php
> +                'created_by'=> User::where('firstname', 'Arthur')->first(),
J'attends Travis mais normalement ici le linter va hurler

2018-12-12 19:43 UTC, arthurlefevre commented on database/seeds/EventsTableSeeder.php
> +                'created_by'=> User::where('firstname', 'Arthur')->first(),
Pourquoi il hurlerait ?

2019-02-19 17:52 UTC, NastuzziSamy commented
Fermée pour innactivitée

2019-02-19 17:52 UTC, closed without merging