[WIP] Feature: Associative career
simde-utc/portail pull request #261
Opened 2019-07-31 14:57 UTC by MercierCorentin

This PR adds the user associative career view in profile.

2019-07-31 15:43 UTC, NastuzziSamy requested changes

2019-07-31 15:43 UTC, NastuzziSamy commented on resources/assets/react/screens/Profile/AssociativeCareer.js
> +		const newSemesters = [];
You create a new array whereas you already got one in your state. Use it directly :)

2019-07-31 15:43 UTC, NastuzziSamy commented on resources/assets/react/screens/Profile/AssociativeCareer.js
> +					newSemesters.push(semester);
You should not push in an array but more in an object.
Here, you think that everything is resolved in order, but if a semester is returned faster, you'll get them in desorder.

Set your state like this: semesters[semester_id] = data

And after, in order to print, create a loop for each semester ;)

2019-07-31 15:43 UTC, NastuzziSamy commented on resources/assets/react/screens/Profile/AssociativeCareer.js
> +							assosBySemesterList = semester.assos.slice().map(asso => {
Never ^^

2019-08-02 12:35 UTC, NastuzziSamy requested changes

2019-08-02 12:35 UTC, NastuzziSamy commented on resources/assets/react/screens/Profile/AssociativeCareer.js
> +		dispatch(actions.config({ title: `${name} - Mon Parcours` }));
Let "Mon parcours", depending on the name of the person, it would be so long

2019-08-02 12:35 UTC, NastuzziSamy commented on resources/assets/react/screens/Profile/AssociativeCareer.js
> +			.slice()
Why ?

2019-08-02 12:35 UTC, NastuzziSamy commented on resources/assets/react/screens/Profile/AssociativeCareer.js
> +			.reverse()
It is asynchornous, no mather the order

2019-08-02 12:35 UTC, NastuzziSamy commented on resources/assets/react/screens/Profile/AssociativeCareer.js
> +		dispatch(actions.config({ title: `${name} - Mon Parcours` }));
Same here

2019-08-02 12:35 UTC, NastuzziSamy commented on resources/assets/react/screens/Profile/AssociativeCareer.js
> +		const objectToAssign = {};
No, no need to create a new object

2019-08-02 12:35 UTC, NastuzziSamy commented on resources/assets/react/screens/Profile/AssociativeCareer.js
> +		this.setState({
Here you can simply do:
`this.setState(prevState => { prevState.associativeSemesters[semester_id] = assos; return prevState; })

2019-08-02 12:35 UTC, NastuzziSamy commented on resources/assets/react/screens/Profile/AssociativeCareer.js
> +						const assosBySemesterList = associativeSemesters[semester_id].slice().map(asso => {
no slice needed, map creates a new array

2019-08-03 11:13 UTC, NastuzziSamy commented on resources/assets/react/screens/Profile/AssociativeCareer.js
> +		dispatch(actions.config({ title: `Mon Parcours` }));
It is better to use simple quotes but np

2019-08-03 11:36 UTC, NastuzziSamy requested changes
Just fix this one :)

2019-08-03 11:36 UTC, NastuzziSamy commented on resources/assets/react/screens/Profile/AssociativeCareer.js
> +										<AssoCard
You should use the MemberCard instead, so you can put a `title` (the shortname association) and a `description` (the role)

2019-08-03 12:53 UTC, MercierCorentin commented
View after last commit:
![image](https://user-images.githubusercontent.com/46066895/62412129-71f96080-b5fe-11e9-978d-c4334d2a08ab.png)

2019-08-03 13:09 UTC, NastuzziSamy approved these changes

2019-08-03 13:10 UTC, merged