Fix roles fetching in AssociativeCareer
simde-utc/portail pull request #263
Opened 2019-08-03 16:36 UTC by MercierCorentin

2019-08-03 18:21 UTC, NastuzziSamy commented on resources/assets/react/screens/Profile/AssociativeCareer.js
> +											additionalInfo={role.name ? role.name : ''}
Haha almost 
`role ? `

2019-08-03 18:21 UTC, NastuzziSamy requested changes
A little detail to fix

2019-08-04 08:02 UTC, MercierCorentin commented on resources/assets/react/screens/Profile/AssociativeCareer.js
> +											additionalInfo={role.name ? role.name : ''}
Should be ok now!

2019-08-04 12:45 UTC, NastuzziSamy approved these changes

2019-08-04 12:45 UTC, merged