Feature: assos cemetery
simde-utc/portail pull request #284
Opened 2019-10-03 18:08 UTC by MercierCorentin

This is a proposition for the asso's cemetary :kissing_heart: 
#132 resolution.

2019-11-06 14:35 UTC, cesar-richard requested changes

2019-11-06 14:35 UTC, cesar-richard commented on app/Console/Commands/Test.php
> +        $this->output->success('Perfect code √');
Mouai le wording ^^Plutot Code Valide :)

2019-11-06 14:35 UTC, cesar-richard commented on database/seeds/AssosTableSeeder.php
> +                'in_cemetery_at' => null,
Bof, pourquoi la valeur n'est pas par defaut a null ? la creation se chargerait de faire tout ca en implicit

2019-11-06 14:35 UTC, cesar-richard commented on resources/assets/react/components/AssoCard.js
> +const AssoCard = ({ image, login, name, shortname, additionalInfo, deleted }) => {
deleted ou inCemetery ?

2019-11-30 22:19 UTC, cesar-richard requested changes

2019-11-30 22:19 UTC, cesar-richard commented on database/migrations/2019_11_22_143951_add_cemetary_assos_table.php
> +<?php
Et donc ca, tu l'as déjà extrait dans une PR a part ?

2019-11-30 23:14 UTC, MercierCorentin commented on database/migrations/2019_11_22_143951_add_cemetary_assos_table.php
> +<?php
Fait!

2019-11-30 23:20 UTC, merged