Added possibility of using alternative ginger provider
simde-utc/portail pull request #349
Opened 2020-03-23 10:46 UTC by noeamiot

Changement du provider Ginger de manière à pouvoir utiliser un autre serveur ginger (je vais essayer de faire des modifs pour proposer un faux ginger, voir autres repo du SiMDE). 

@MercierCorentin Petite question cependant, je me base sur la valeur de la variable d'environement pour l'URL de Ginger mais j'ai pas mis de valeur par défaut. Pour la mise en prod, il faudra soit que je rajoute une valeur par défaut qui est celle de la prod (pas beau) soit il faudra penser à rajouter la valeur dans le .env sur le serveur !

2020-03-23 10:57 UTC, MercierCorentin requested changes
Sympa!
Tu peux update la doc d'installation et celle du service Ginger du coup?
Dans la même PR serait idéal!
Rendu de la doc du Service Ginger: https://simde.gitlab.utc.fr/documentation/#/portail/dev/backend/services/ginger
Rendu de la doc d'Installation: https://simde.gitlab.utc.fr/documentation/#/portail/dev/installation

2020-03-23 14:30 UTC, noeamiot commented
J'ai revu quelques trucs par rapport au fake Ginger, donc attend avant de merge, je vais rajouter des trucs sur le faux ginger.

2020-03-25 07:31 UTC, MercierCorentin commented
J'ai eu un petit pb avec les notices de PHP. Du coup j'ai PR sur faux-ginger les petits fix. 

Explication de mon dernier commit:
- Ajout des valeurs par défaut dans le `.env.example` (Le `V1/` à la fin de l'url est pas très évident si on a pas d'exemple)
- Correction d'un coquille et du rendu de la doc (tes points de la liste à puce s'affichaient sur une seul ligne sur mon rendu local de la doc)

2020-03-28 08:14 UTC, MercierCorentin approved these changes

2020-03-28 08:14 UTC, merged